apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  labels:
    app: test-app 
spec:
  selector:
    app: test-app

  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # Vous pouvez spécifier un nodePort si nécessaire

  type: NodePort
